In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.linear_regression import simple_linear_regression, multi_linear_regression
import numpy as np
import pandas as pd

advertising = pd.read_csv('../data/Advertising.csv')

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
advertising = advertising.iloc[:, 1:]
advertising

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
x = advertising['TV'].values
y = advertising['Sales'].values
simple_model = simple_linear_regression(x,y)


β0 = 7 .03 and β1 = 0 .047

# Testing Simple Linear Regression

In [5]:
simple_model.parameters

(7.0325935491276965, 0.047536640433019736)

In [6]:
simple_model._get_rss()

2102.5305831313512

In [7]:
simple_model.get_confidence_intervals()

{'95% Confidence Interval For β1': [0.042, 0.053],
 '95% Confidence Interval For β0': [6.117, 7.948]}

In [8]:
simple_model.get_significance()

Parameter  Coefficient  std_error  t-statistic       p-value
0        B0     7.032594   0.457843    15.360275  7.336949e-43
1        B1     0.047537   0.002691    17.667626  7.031502e-36

In [9]:
simple_model.std_errors

(0.4578429402734785, 0.0026906071877968707)

In [10]:
simple_model._get_r_squared()

2102.5305831313512 5417.14875


0.611875050850071

In [34]:
x_multi = advertising.iloc[:, :3].values
print(x_multi.shape)
print(y.shape)
multi_model = multi_linear_regression(x_multi,y)

(200, 3)
(200,)


In [6]:

multi_model._minimize_rss()

array([[ 2.93888937e+00],
       [ 4.57646455e-02],
       [ 1.88530017e-01],
       [-1.03749304e-03]])

In [7]:
multi_model._avg_x()

array([  1.    , 147.0425,  23.264 ,  30.554 ])

In [8]:
multi_model.x

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
 

In [25]:
multi_model._get_rse()

1.6812269856174873

In [35]:
multi_model._get_std_errors()

2.8265241771684626
(4, 4)
[[  -14.14213562 -2079.49497745  -329.00264315  -432.09881185]
 [    0.          1211.12304443    11.47912763    17.40365778]
 [    0.             0.          -209.12520276  -107.99807815]
 [    0.             0.             0.          -287.09037708]]


array([[ 9.67929065e-02, -2.64378468e-04, -1.10982708e-03,
        -5.88021132e-04],
       [-2.64378468e-04,  1.93586026e-06, -4.44770227e-07,
        -3.24937184e-07],
       [-1.10982708e-03, -4.44770227e-07,  7.37769375e-05,
        -1.77102660e-05],
       [-5.88021132e-04, -3.24937184e-07, -1.77102660e-05,
         3.42937860e-05]])

In [ ]:
array([[ 9.67929065e-02, -2.64378468e-04, -1.10982708e-03, -5.88021132e-04],
       [-2.64378468e-04,  1.93586026e-06, -4.44770227e-07, -3.24937184e-07],
       [-1.10982708e-03, -4.44770227e-07,  7.37769375e-05, -1.77102660e-05],
       [-5.88021132e-04, -3.24937184e-07, -1.77102660e-05, 3.42937860e-05]])

In [28]:
# import sys
# !{sys.executable} -m pip install --user sklearn

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
test_linear = LinearRegression()

In [27]:
test_linear.fit(x_multi, y)

LinearRegression()

In [31]:
display(test_linear.coef_)
display(test_linear.intercept_)

array([ 0.04576465,  0.18853002, -0.00103749])

2.938889369459412

In [36]:
x_multi.shape[0]

200